# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Teclib'.GLPIAgent1.7.2
PackageVersion: 1.7.2
PackageLocale: en-US
Publisher: Teclib'
PackageName: GLPI Agent 1.7.2
License: MIT
ShortDescription: GLPI Agent 1.7.2
ManifestType: defaultLocale
ManifestVersion: 1.6.0
